name: artemis
version: 6.18.4

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  build_config: ^1.1.1
  build: ^2.4.1
  code_builder: ^4.3.0
  collection: ^1.14.13
  dart_style: ^2.0.0
  equatable: ^2.0.5
  glob: ^2.1.2
  gql_code_builder: ^0.8.0
  gql_dedupe_link: ^2.0.4-alpha+1691943394662
  gql_exec: ^1.0.0
  gql_http_link: ^1.0.1
  gql_link: ^1.0.1-alpha+1691943394596
  gql: ^1.0.0
  http: ^1.1.0
  json_annotation: ^4.0.1
  meta: ^1.2.4
  path: ^1.7.0
  recase: ^4.1.0
  source_gen: ^1.4.0
  yaml: ^3.1.2

dev_dependencies:
  args: ^2.4.2
  build_runner: ^2.4.6
  build_test: ^2.2.0
  json_serializable: ^6.7.1
  build_resolvers: ^2.3.2
  lints: ^2.1.1
  test: ^1.15.7
  logging: ^1.2.0
